Fix misconfigs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,7 +29,7 @@ on:
           description: "Skip build phase"
           type: boolean
           required: true
-          default: true
+          default: false
 
 env:
   DOCKER_BUILDER_IMAGE: mangatasolutions/node-builder:0.2
@@ -46,147 +46,146 @@ jobs:
         id: set_ver
         run: echo "::set-output name=GLOBAL_VERSION::${{ github.sha }}"
 
-  rustfmt-check:
-    name: Formatting check
-    if:  ${{ github.event.inputs.skipBuild != 'true' }}
-    runs-on: ubuntu-latest
-    steps:
-      -
-        name: Checkout
-        uses: actions/checkout@v2
-      -
-        name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
-      -
-        name: Login to Docker Hub
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      - name: Pull builder image
-        run: |
-          docker pull ${{ env.DOCKER_BUILDER_IMAGE }}
-      -
-        name: Check formatting
-        run: |
-          ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch
-          ./docker-cargo.sh fmt --all -- --check
+  # rustfmt-check:
+  #   name: Formatting check
+  #   if:  ${{ github.event.inputs.skipBuild != 'true' }}
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     -
+  #       name: Checkout
+  #       uses: actions/checkout@v2
+  #     -
+  #       name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v1
+  #     -
+  #       name: Login to Docker Hub
+  #       uses: docker/login-action@v1
+  #       with:
+  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
+  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
+  #     - name: Pull builder image
+  #       run: |
+  #         docker pull ${{ env.DOCKER_BUILDER_IMAGE }}
+  #     -
+  #       name: Check formatting
+  #       run: |
+  #         ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch
+  #         ./docker-cargo.sh fmt --all -- --check
 
-  clippy-check:
-    name: Clippy check
-    runs-on: ubuntu-latest
-    if: ${{ github.event.inputs.skipBuild != 'true' }}
-    steps:
-      -
-        name: Checkout
-        uses: actions/checkout@v2
-      -
-        name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
-      -
-        name: Login to Docker Hub
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      - name: Pull builder image
-        run: |
-          docker pull ${{ env.DOCKER_BUILDER_IMAGE }}
-      -
-        name: Run clippy
-        run: |
-          ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch
-          ./docker-cargo.sh clippy -p pallet-xyk
+  # clippy-check:
+  #   name: Clippy check
+  #   runs-on: ubuntu-latest
+  #   if: ${{ github.event.inputs.skipBuild != 'true' }}
+  #   steps:
+  #     -
+  #       name: Checkout
+  #       uses: actions/checkout@v2
+  #     -
+  #       name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v1
+  #     -
+  #       name: Login to Docker Hub
+  #       uses: docker/login-action@v1
+  #       with:
+  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
+  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
+  #     - name: Pull builder image
+  #       run: |
+  #         docker pull ${{ env.DOCKER_BUILDER_IMAGE }}
+  #     -
+  #       name: Run clippy
+  #       run: |
+  #         ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch
+  #         ./docker-cargo.sh clippy -p pallet-xyk
 
-  unit-test:
-    name: Unit test
-    runs-on: ubuntu-latest
-    if: ${{ github.event.inputs.skipBuild != 'true' }}
-    steps:
-      -
-        name: Checkout
-        uses: actions/checkout@v2
-      -
-        name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
-      -
-        name: Login to Docker Hub
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      - name: Pull builder image
-        run: |
-          docker pull ${{ env.DOCKER_BUILDER_IMAGE }}
-      -
-        name: Run unit tests
-        run: |
-          ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch
-          ./docker-cargo.sh test -j2 -p pallet-bootstrap -p xyk-rpc -p pallet-xyk -p xyk-runtime-api -p pallet-issuance -p pallet-multipurpose-liquidity -p pallet-sudo-origin
+  # unit-test:
+  #   name: Unit test
+  #   runs-on: ubuntu-latest
+  #   if: ${{ github.event.inputs.skipBuild != 'true' }}
+  #   steps:
+  #     -
+  #       name: Checkout
+  #       uses: actions/checkout@v2
+  #     -
+  #       name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v1
+  #     -
+  #       name: Login to Docker Hub
+  #       uses: docker/login-action@v1
+  #       with:
+  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
+  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
+  #     - name: Pull builder image
+  #       run: |
+  #         docker pull ${{ env.DOCKER_BUILDER_IMAGE }}
+  #     -
+  #       name: Run unit tests
+  #       run: |
+  #         ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch
+  #         ./docker-cargo.sh test -j2 -p pallet-bootstrap -p xyk-rpc -p pallet-xyk -p xyk-runtime-api -p pallet-issuance -p pallet-multipurpose-liquidity -p pallet-sudo-origin
 
-          # |cargo2junit | tee ut-results.xml
-          # sed -i '/<testsuite.*\/>$/d' ut-results.xml
-          # sed -i 's/<testsuites>/<testsuites time="0">/g' ut-results.xml
-          # cat ut-results.xml
-      # - name: Test Report
-      #   uses: dorny/test-reporter@v1
-      #   if: success() || failure()
-      #   with:
-      #     name: Unit Tests
-      #     path: ut-results.xml
-      #     reporter: jest-junit
+  #         # |cargo2junit | tee ut-results.xml
+  #         # sed -i '/<testsuite.*\/>$/d' ut-results.xml
+  #         # sed -i 's/<testsuites>/<testsuites time="0">/g' ut-results.xml
+  #         # cat ut-results.xml
+  #     # - name: Test Report
+  #     #   uses: dorny/test-reporter@v1
+  #     #   if: success() || failure()
+  #     #   with:
+  #     #     name: Unit Tests
+  #     #     path: ut-results.xml
+  #     #     reporter: jest-junit
 
-  run-benchmarks-tests:
-    name: Run benchmark tests
-    runs-on: ubuntu-latest
-    if: ${{ github.event.inputs.skipBuild != 'true' }}
-    steps:
-      - uses: actions/checkout@v2
-      - uses: docker/setup-buildx-action@v1
-      - uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
+  # run-benchmarks-tests:
+  #   name: Run benchmark tests
+  #   runs-on: ubuntu-latest
+  #   if: ${{ github.event.inputs.skipBuild != 'true' }}
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - uses: docker/setup-buildx-action@v1
+  #     - uses: docker/login-action@v1
+  #       with:
+  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
+  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Pull builder image
-        run: docker pull ${{ env.DOCKER_BUILDER_IMAGE }}
-      - name: Run benchamrks
-        run: |
-          ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch
-          ./docker-cargo.sh test -j2 --features=runtime-benchmarks -p pallet-bootstrap -p pallet-xyk -p xyk-runtime-api -p pallet-issuance
+  #     - name: Pull builder image
+  #       run: docker pull ${{ env.DOCKER_BUILDER_IMAGE }}
+  #     - name: Run benchamrks
+  #       run: |
+  #         ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch
+  #         ./docker-cargo.sh test -j2 --features=runtime-benchmarks -p pallet-bootstrap -p pallet-xyk -p xyk-runtime-api -p pallet-issuance
 
-  build-node-image:
-    needs: [init]
-    runs-on: [self-hosted, compile]
-    if: ${{ github.event.inputs.skipBuild != 'true' }}
-    steps:
-      - name: Debug info about publishing.
-        run: echo ${{ github.ref }} == 'refs/heads/develop' && echo ${{ github.ref }}
-      - uses: actions/checkout@v3
-      - uses: docker/setup-buildx-action@v1
-      - uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
+  # build-node-image:
+  #   needs: [init]
+  #   runs-on: [self-hosted, compile]
+  #   if: ${{ github.event.inputs.skipBuild != 'true' }}
+  #   steps:
+  #     - name: Debug info about publishing.
+  #       run: echo ${{ github.ref }} == 'refs/heads/develop' && echo ${{ github.ref }}
+  #     - uses: actions/checkout@v3
+  #     - uses: docker/setup-buildx-action@v1
+  #     - uses: docker/login-action@v1
+  #       with:
+  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
+  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Build and push
-        uses: docker/build-push-action@v3
-        with:
-          push: true
-          file: devops/dockerfiles/node-new/Dockerfile
-          cache-from: type=registry,ref=mangatasolutions/mangata-node
-          cache-to: type=registry,ref=mangatasolutions/mangata-node,mode=max
-          tags: |
-            "mangatasolutions/mangata-node:${{ needs.init.outputs.GLOBAL_VERSION }}"
-            "mangatasolutions/mangata-node:rococo-${{ needs.init.outputs.GLOBAL_VERSION }}"
-            "mangatasolutions/mangata-node:kusama-${{ needs.init.outputs.GLOBAL_VERSION }}"
+  #     - name: Build and push
+  #       uses: docker/build-push-action@v3
+  #       with:
+  #         push: true
+  #         file: devops/dockerfiles/node-new/Dockerfile
+  #         cache-from: type=registry,ref=mangatasolutions/mangata-node
+  #         cache-to: type=registry,ref=mangatasolutions/mangata-node,mode=max
+  #         tags: |
+  #           "mangatasolutions/mangata-node:${{ needs.init.outputs.GLOBAL_VERSION }}"
+  #           "mangatasolutions/mangata-node:rococo-${{ needs.init.outputs.GLOBAL_VERSION }}"
+  #           "mangatasolutions/mangata-node:kusama-${{ needs.init.outputs.GLOBAL_VERSION }}"
 
   build-and-run-try-runtime:
-    needs: [init]
     runs-on: [self-hosted, compile]
     container:
       image: paritytech/ci-linux:production
-    if: ${{ github.event.inputs.skipBuild == 'true' }}
+    if: ${{ github.event.inputs.skipBuild != 'true' }}
     steps:
       - uses: actions/checkout@v3
       - uses: 'google-github-actions/auth@v0'
@@ -210,18 +209,18 @@ jobs:
       - name: Run try-runtime
         run: cargo run --release --features=try-runtime try-runtime --chain=kusama-mainnet --execution=Native on-runtime-upgrade live --uri wss://prod-kusama-collator-01.mangatafinance.cloud:443
 
-  run-benchmarks:
-    name: Run runtime benchmarks
-    needs: [init,build-node-image]
-    runs-on: ubuntu-latest
-    if: ${{ github.event.inputs.skipBuild != 'true' }}
-    env:
-      NODE_IMAGE: ${{ format('mangatasolutions/mangata-node:rococo-{0}', needs.init.outputs.GLOBAL_VERSION) }}
-    steps:
-      - name: Run Runtime Benchmark
-        run: |
-          docker pull ${{ env.NODE_IMAGE }}
-          docker run --rm ${{ env.NODE_IMAGE }} benchmark pallet --chain kusama-mainnet --execution wasm --wasm-execution compiled --extrinsic '*' --pallet 'pallet-xyk' --template ./templates/module-weight-template.hbs
+  # run-benchmarks:
+  #   name: Run runtime benchmarks
+  #   needs: [init,build-node-image]
+  #   runs-on: ubuntu-latest
+  #   if: ${{ github.event.inputs.skipBuild != 'true' }}
+  #   env:
+  #     NODE_IMAGE: ${{ format('mangatasolutions/mangata-node:rococo-{0}', needs.init.outputs.GLOBAL_VERSION) }}
+  #   steps:
+  #     - name: Run Runtime Benchmark
+  #       run: |
+  #         docker pull ${{ env.NODE_IMAGE }}
+  #         docker run --rm ${{ env.NODE_IMAGE }} benchmark pallet --chain kusama-mainnet --execution wasm --wasm-execution compiled --extrinsic '*' --pallet 'pallet-xyk' --template ./templates/module-weight-template.hbs
 
   # e2e-test-matrix:
   #   strategy:
