split e2e tests into 2 parallell jobs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -306,8 +306,8 @@ jobs:
             ./docker-cargo/release/wbuild/mangata-kusama-runtime/mangata_kusama_runtime.compact.compressed.wasm
             ./docker-cargo/release/wbuild/mangata-kusama-runtime/mangata_kusama_runtime.compact.compressed.wasm.md5
 
-  e2e-test:
-    needs: build-rococo-e2e
+  e2e-test-parallel:
+    needs: build-rococo
     runs-on: self-hosted
     if: "!contains(github.event.pull_request.labels.*.name, 'skip-e2e-tests')"
     env:
@@ -319,7 +319,7 @@ jobs:
       TEST_SUDO_NAME: ${{ secrets.E2E_TEST_SUDO_NAME }}
       MANGATA_NODE_VERSION: ${{ github.sha }}
       E2EBRANCHNAME: 'main'
-      PARACHAIN_DOCKER_IMAGE: "${{ github.event.inputs.parachainDocker || 'mangatasolutions/mangata-node:rococo-e2e-latest' }}"
+      PARACHAIN_DOCKER_IMAGE: "${{ github.event.inputs.parachainDocker || 'mangatasolutions/mangata-node:rococo-latest' }}"
     steps:
     ####IDK, but this is neccesary for reports
       -
@@ -331,13 +331,150 @@ jobs:
         if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-build') && github.event.inputs.skipBuild != 'true' }}
         uses: actions/download-artifact@v2
         with:
-          name: rococo-docker-e2e-${{ github.sha }}
+          name: rococo-docker-${{ github.sha }}
           path: /tmp
       -
         name: Load Docker image
         if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-build') && github.event.inputs.skipBuild != 'true' }}
         run: |
-          docker load --input /tmp/rococo-docker-e2e-${{ github.sha }}.tar
+          docker load --input /tmp/rococo-docker-${{ github.sha }}.tar
+          docker image ls -a
+
+      - name: E2E- Get branch name
+        id: branch-name
+        uses: tj-actions/branch-names@v4.9
+
+      - name: E2E- Get target branch. 
+        run: |
+          echo "This job name branch is: ${{ steps.branch-name.outputs.current_branch }}"
+
+      - name: E2E- Calculate if run e2e feature branch or main.
+        run: |
+          echo DEFAULT: E2E test will run with: $E2EBRANCHNAME
+          echo "Running on: ${{ steps.branch-name.outputs.current_branch }}"
+          if [ -n "$(git ls-remote --heads https://github.com/mangata-finance/mangata-e2e.git ${{ steps.branch-name.outputs.current_branch }} --force --quiet)" ]; then echo "E2EBRANCHNAME=${{ steps.branch-name.outputs.current_branch }}" >> $GITHUB_ENV; echo "MATCH - OK" ; elif [ -n "$(git ls-remote --heads https://github.com/mangata-finance/mangata-e2e.git ${{ github.base_ref }} --force --quiet)" ]; then echo "E2EBRANCHNAME=${{ github.base_ref }}" >> $GITHUB_ENV; echo "MATCH - OK" ;  fi
+
+      - name: Decide if main - branch or parameter
+      # if we have something in e2eBranch - override E2EBranchName, else -> E2EBRANCHNAME , that
+      # by default will be main. 
+
+        run: 
+          echo "E2EBRANCHNAME=${{ github.event.inputs.e2eBranch || env.E2EBRANCHNAME }}" >> $GITHUB_ENV
+
+      - name: E2E- Get target branch. 
+        run: |
+         echo "${{ env.E2EBRANCHNAME }}"
+
+      - 
+        name: Checkout tests
+        uses: actions/checkout@v2
+        with:
+          repository: mangata-finance/mangata-e2e
+          ref: '${{ env.E2EBRANCHNAME }}'
+          path: 'e2eTests'
+
+      - name: Print parachain docker image reference
+        run: |
+          echo ${{ env.PARACHAIN_DOCKER_IMAGE }}
+
+      - name: Stop previous parachain if running
+        run: make -C devops/parachain stop
+
+      - name: Start mangata-node parachain
+        env:
+          ENV: rococo
+        run: make -C devops/parachain start
+
+      - name: Install dependencies
+        working-directory: e2eTests
+        run: yarn
+
+      - name: Docker ps
+        run: docker ps
+
+      - name: Sleep for 2 minutes
+        run: sleep 120s #close buffers of videos.
+
+      - name: Run parallel e2e tests
+        working-directory: e2eTests
+        run: yarn test-parallel
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: JEST Tests            # Name of the check run which will be created
+          path: e2eTests/reports/junit-*.xml    # Path to test results
+          reporter: jest-junit        # Format of test results
+
+      - name: Collect docker logs on failure
+        if: failure()
+        uses: jwalton/gh-docker-logs@v1
+        with:
+          images: 'mangata,polkadot'
+          dest: './logs'
+
+      - name: Tar logs
+        if: failure()
+        run: tar cvzf ./logs.tgz ./logs
+
+      - name: Create images snapshots
+        if: failure()
+        run: |
+          docker commit  $(docker ps | grep mangata | grep bob | awk '{print $1}') mangata_test_run/mangata_bob_1
+          docker save  --output=/tmp/mangata_bob_1.tar mangata_test_run/mangata_bob_1
+          docker commit  $(docker ps | grep mangata | grep alice | awk '{print $1}') mangata_test_run/mangata_alice_1
+          docker save  --output=/tmp/mangata_alice_1.tar mangata_test_run/mangata_alice_1
+
+      - name: Upload logs  and docker images to GitHub
+        if: failure()
+        uses: actions/upload-artifact@master
+        with:
+          name: logsAndImages
+          path: |
+            ./logs.tgz
+            /tmp/mangata_bob_1.tar
+            /tmp/mangata_alice_1.tar
+
+      - name: Stop mangata-node parachain
+        if: always()
+        run: |
+          make -C devops/parachain stop
+          docker system prune -a -f
+
+
+  e2e-test-sequential:
+    needs: build-rococo
+    runs-on: self-hosted
+    if: "!contains(github.event.pull_request.labels.*.name, 'skip-e2e-tests')"
+    env:
+      API_URL: 'ws://127.0.0.1:8844'
+      TEST_PALLET_ADDRESS: ${{ secrets.E2E_TEST_PALLET_ADDRESS }}
+      E2E_TREASURY_PALLET_ADDRESS : ${{ secrets.E2E_TREASURY_PALLET_ADDRESS }}
+      E2E_XYK_PALLET_ADDRESS : ${{ secrets.E2E_XYK_PALLET_ADDRESS }} 
+      E2E_TREASURY_BURN_PALLET_ADDRESS : ${{ secrets.E2E_TREASURY_BURN_PALLET_ADDRESS }}
+      TEST_SUDO_NAME: ${{ secrets.E2E_TEST_SUDO_NAME }}
+      MANGATA_NODE_VERSION: ${{ github.sha }}
+      E2EBRANCHNAME: 'main'
+      PARACHAIN_DOCKER_IMAGE: "${{ github.event.inputs.parachainDocker || 'mangatasolutions/mangata-node:rococo-latest' }}"
+    steps:
+    ####IDK, but this is neccesary for reports
+      -
+        name: Checkout
+        uses: actions/checkout@v2
+
+      -
+        name: Download artifact
+        if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-build') && github.event.inputs.skipBuild != 'true' }}
+        uses: actions/download-artifact@v2
+        with:
+          name: rococo-docker-${{ github.sha }}
+          path: /tmp
+      -
+        name: Load Docker image
+        if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-build') && github.event.inputs.skipBuild != 'true' }}
+        run: |
+          docker load --input /tmp/rococo-docker-${{ github.sha }}.tar
           docker image ls -a
 
       - name: E2E- Get branch name
@@ -399,10 +536,6 @@ jobs:
         working-directory: e2eTests
         run: yarn test-sequential-e2e
 
-      - name: Run parallel e2e tests
-        working-directory: e2eTests
-        run: yarn test-parallel
-
       - name: Test Report
         uses: dorny/test-reporter@v1
         if: success() || failure()    # run this step even if previous step failed
@@ -447,7 +580,7 @@ jobs:
           docker system prune -a -f
 
   publish:
-    needs: [rustfmt-check, unit-test, clippy-check, build-rococo, build-kusama, e2e-test, run-benchmarks, run-benchmarks-tests]
+    needs: [rustfmt-check, unit-test, clippy-check, build-rococo, build-kusama, e2e-test-sequential, e2e-test-parallel, run-benchmarks, run-benchmarks-tests]
     runs-on: ubuntu-latest
     if: |
       github.ref == 'refs/heads/develop' && 
