MGX-55: Update CI pipeline and test dev env deployment

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,9 +6,9 @@ name: Continous Integration
 ## skip-publish: skip publish
 
 on:
-  # pull_request:
-  #   branches:
-  #     - develop
+  pull_request:
+    branches:
+      - develop
   push:
     branches: [develop]
 
@@ -34,6 +34,7 @@ on:
 env:
   DOCKER_BUILDER_IMAGE: mangatasolutions/node-builder:0.2
   DISABLE_TTY: 1
+  version: dev
 
 jobs:
   init:
@@ -46,23 +47,66 @@ jobs:
         id: set_ver
         run: echo "GLOBAL_VERSION=${{ github.sha }}" >> $GITHUB_OUTPUT
 
+  build-node-image:
+    needs: [init]
+    runs-on: [self-hosted, compile]
+    if: ${{ github.event.inputs.skipBuild != 'true' }}
+    steps:
+      - name: Debug info about publishing.
+        run: echo ${{ github.ref }} == 'refs/heads/develop' && echo ${{ github.ref }}
+      - uses: actions/checkout@v3
+      - uses: docker/setup-buildx-action@v2.2.1
+      - uses: docker/login-action@v2.1.0
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - name: Build and push
+        uses: docker/build-push-action@v3.2.0
+        with:
+          push: true
+          file: devops/dockerfiles/node-new/Dockerfile
+          cache-from: type=registry,ref=mangatasolutions/mangata-node
+          cache-to: type=registry,ref=mangatasolutions/mangata-node,mode=max
+          tags: |
+            "mangatasolutions/mangata-node:${{ needs.init.outputs.GLOBAL_VERSION }}"
+            "mangatasolutions/mangata-node:rococo-${{ needs.init.outputs.GLOBAL_VERSION }}"
+            "mangatasolutions/mangata-node:kusama-${{ needs.init.outputs.GLOBAL_VERSION }}"
+  deploy:
+    permissions:
+      contents: 'read'
+      id-token: 'write'
+    runs-on: ubuntu-latest
+    needs: [init,build-node-image]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+      - uses: google-github-actions/auth@v1
+        with:
+          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
+          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
+      - name: Set up GKE credentials
+        uses: google-github-actions/get-gke-credentials@v0.8.0
+        with:
+          cluster_name: mangata-dev
+          location: europe-west1
+      
+      - uses: jkroepke/setup-vals@v1.0.4
+      - run: |
+          helm plugin install https://github.com/jkroepke/helm-secrets --version v4.1.1
+          helm secrets -b vals upgrade -i --create-namespace -n ${{ env.version }} --wait node . \
+          --set image.tag=${{ needs.init.outputs.GLOBAL_VERSION }} \
+          -f values.yaml -f values-dev.yaml
+        working-directory: devops/helm-charts/node
+
   rustfmt-check:
     name: Formatting check
     if: ${{ github.event.inputs.skipBuild != 'true' }}
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
-      - name: Login to Docker Hub
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
+      - uses: actions/checkout@v3
       - name: Pull builder image
-        run: |
-          docker pull ${{ env.DOCKER_BUILDER_IMAGE }}
+        run: docker pull ${{ env.DOCKER_BUILDER_IMAGE }}
       - name: Check formatting
         run: |
           ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch
@@ -74,17 +118,9 @@ jobs:
     if: ${{ github.event.inputs.skipBuild != 'true' }}
     steps:
       - name: Checkout
-        uses: actions/checkout@v2
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
-      - name: Login to Docker Hub
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
+        uses: actions/checkout@v3
       - name: Pull builder image
-        run: |
-          docker pull ${{ env.DOCKER_BUILDER_IMAGE }}
+        run: docker pull ${{ env.DOCKER_BUILDER_IMAGE }}
       - name: Run clippy
         run: |
           ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch
@@ -95,79 +131,26 @@ jobs:
     runs-on: ubuntu-latest
     if: ${{ github.event.inputs.skipBuild != 'true' }}
     steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
-      - name: Login to Docker Hub
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
+      - uses: actions/checkout@v3
       - name: Pull builder image
-        run: |
-          docker pull ${{ env.DOCKER_BUILDER_IMAGE }}
+        run: docker pull ${{ env.DOCKER_BUILDER_IMAGE }}
       - name: Run unit tests
         run: |
           ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch
           ./docker-cargo.sh test -j2 -p pallet-bootstrap -p xyk-rpc -p pallet-xyk -p xyk-runtime-api -p pallet-issuance -p pallet-multipurpose-liquidity -p pallet-sudo-origin
-
-          # |cargo2junit | tee ut-results.xml
-          # sed -i '/<testsuite.*\/>$/d' ut-results.xml
-          # sed -i 's/<testsuites>/<testsuites time="0">/g' ut-results.xml
-          # cat ut-results.xml
-      # - name: Test Report
-      #   uses: dorny/test-reporter@v1
-      #   if: success() || failure()
-      #   with:
-      #     name: Unit Tests
-      #     path: ut-results.xml
-      #     reporter: jest-junit
 
   run-benchmarks-tests:
     name: Run benchmark tests
     runs-on: ubuntu-latest
     if: ${{ github.event.inputs.skipBuild != 'true' }}
     steps:
-      - uses: actions/checkout@v2
-      - uses: docker/setup-buildx-action@v1
-      - uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-
+      - uses: actions/checkout@v3
       - name: Pull builder image
         run: docker pull ${{ env.DOCKER_BUILDER_IMAGE }}
       - name: Run benchamrks
         run: |
           ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch
           ./docker-cargo.sh test -j2 --features=runtime-benchmarks -p pallet-bootstrap -p pallet-xyk -p xyk-runtime-api -p pallet-issuance
-
-  build-node-image:
-    needs: [init]
-    runs-on: [self-hosted, compile]
-    if: ${{ github.event.inputs.skipBuild != 'true' }}
-    steps:
-      - name: Debug info about publishing.
-        run: echo ${{ github.ref }} == 'refs/heads/develop' && echo ${{ github.ref }}
-      - uses: actions/checkout@v3
-      - uses: docker/setup-buildx-action@v1
-      - uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-
-      - name: Build and push
-        uses: docker/build-push-action@v3
-        with:
-          push: true
-          file: devops/dockerfiles/node-new/Dockerfile
-          cache-from: type=registry,ref=mangatasolutions/mangata-node
-          cache-to: type=registry,ref=mangatasolutions/mangata-node,mode=max
-          tags: |
-            "mangatasolutions/mangata-node:${{ needs.init.outputs.GLOBAL_VERSION }}"
-            "mangatasolutions/mangata-node:rococo-${{ needs.init.outputs.GLOBAL_VERSION }}"
-            "mangatasolutions/mangata-node:kusama-${{ needs.init.outputs.GLOBAL_VERSION }}"
 
   build-and-run-try-runtime:
     runs-on: [self-hosted, compile]
@@ -209,138 +192,138 @@ jobs:
           docker pull ${{ env.NODE_IMAGE }}
           docker run --rm ${{ env.NODE_IMAGE }} benchmark pallet --chain kusama-mainnet --execution wasm --wasm-execution compiled --extrinsic '*' --pallet 'pallet-xyk' --template ./templates/module-weight-template.hbs
 
-  e2e-test-matrix:
-    strategy:
-      matrix:
-        command: ["yarn test-parallel --max-workers=32", "yarn test-sequential-e2e"]
-    needs: [init, build-node-image]
-    runs-on: [self-hosted, basic]
-    timeout-minutes: 180
-    if: ${{ (!cancelled() && (success() || github.event.inputs.skipBuild == 'true')) && !contains(github.event.pull_request.labels.*.name, 'skip-e2e-tests') }}
-    env:
-      API_URL: "ws://127.0.0.1:9946"
-      TEST_PALLET_ADDRESS: ${{ secrets.E2E_TEST_PALLET_ADDRESS }}
-      E2E_TREASURY_PALLET_ADDRESS: ${{ secrets.E2E_TREASURY_PALLET_ADDRESS }}
-      E2E_XYK_PALLET_ADDRESS: ${{ secrets.E2E_XYK_PALLET_ADDRESS }}
-      E2E_TREASURY_BURN_PALLET_ADDRESS: ${{ secrets.E2E_TREASURY_BURN_PALLET_ADDRESS }}
-      #      TEST_SUDO_NAME: ${{ secrets.E2E_TEST_SUDO_NAME }}
-      TEST_SUDO_NAME: "//Alice"
-      MANGATA_NODE_VERSION: ${{ needs.init.outputs.GLOBAL_VERSION }}
-      E2EBRANCHNAME: "main"
-      PARACHAIN_DOCKER_IMAGE: ${{ github.event.inputs.parachainDocker || format('mangatasolutions/mangata-node:rococo-{0}', needs.init.outputs.GLOBAL_VERSION) }}
-    steps:
-      ####IDK, but this is neccesary for reports
-      - uses: actions/checkout@v3
+  # e2e-test-matrix:
+  #   strategy:
+  #     matrix:
+  #       command: ["yarn test-parallel --max-workers=32", "yarn test-sequential-e2e"]
+  #   needs: [init, build-node-image]
+  #   runs-on: [self-hosted, basic]
+  #   timeout-minutes: 180
+  #   if: ${{ (!cancelled() && (success() || github.event.inputs.skipBuild == 'true')) && !contains(github.event.pull_request.labels.*.name, 'skip-e2e-tests') }}
+  #   env:
+  #     API_URL: "ws://127.0.0.1:9946"
+  #     TEST_PALLET_ADDRESS: ${{ secrets.E2E_TEST_PALLET_ADDRESS }}
+  #     E2E_TREASURY_PALLET_ADDRESS: ${{ secrets.E2E_TREASURY_PALLET_ADDRESS }}
+  #     E2E_XYK_PALLET_ADDRESS: ${{ secrets.E2E_XYK_PALLET_ADDRESS }}
+  #     E2E_TREASURY_BURN_PALLET_ADDRESS: ${{ secrets.E2E_TREASURY_BURN_PALLET_ADDRESS }}
+  #     #      TEST_SUDO_NAME: ${{ secrets.E2E_TEST_SUDO_NAME }}
+  #     TEST_SUDO_NAME: "//Alice"
+  #     MANGATA_NODE_VERSION: ${{ needs.init.outputs.GLOBAL_VERSION }}
+  #     E2EBRANCHNAME: "main"
+  #     PARACHAIN_DOCKER_IMAGE: ${{ github.event.inputs.parachainDocker || format('mangatasolutions/mangata-node:rococo-{0}', needs.init.outputs.GLOBAL_VERSION) }}
+  #   steps:
+  #     ####IDK, but this is neccesary for reports
+  #     - uses: actions/checkout@v3
 
-      - name: Download node Docker image
-        if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-build') && github.event.inputs.skipBuild != 'true' }}
-        run: docker pull ${{ env.PARACHAIN_DOCKER_IMAGE }}
+  #     - name: Download node Docker image
+  #       if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-build') && github.event.inputs.skipBuild != 'true' }}
+  #       run: docker pull ${{ env.PARACHAIN_DOCKER_IMAGE }}
 
-      - name: E2E- Get branch name
-        id: branch-name
-        uses: tj-actions/branch-names@v4.9
+  #     - name: E2E- Get branch name
+  #       id: branch-name
+  #       uses: tj-actions/branch-names@v4.9
 
-      - name: E2E- Get target branch.
-        run: |
-          echo "This job name branch is: ${{ steps.branch-name.outputs.current_branch }}"
+  #     - name: E2E- Get target branch.
+  #       run: |
+  #         echo "This job name branch is: ${{ steps.branch-name.outputs.current_branch }}"
 
-      - name: E2E- Calculate if run e2e feature branch or main.
-        run: |
-          echo DEFAULT: E2E test will run with: $E2EBRANCHNAME
-          echo "Running on: ${{ steps.branch-name.outputs.current_branch }}"
-          if [ -n "$(git ls-remote --heads https://github.com/mangata-finance/mangata-e2e.git ${{ steps.branch-name.outputs.current_branch }} --force --quiet)" ]; then echo "E2EBRANCHNAME=${{ steps.branch-name.outputs.current_branch }}" >> $GITHUB_ENV; echo "MATCH - OK" ; elif [ -n "$(git ls-remote --heads https://github.com/mangata-finance/mangata-e2e.git ${{ github.base_ref }} --force --quiet)" ]; then echo "E2EBRANCHNAME=${{ github.base_ref }}" >> $GITHUB_ENV; echo "MATCH - OK" ;  fi
+  #     - name: E2E- Calculate if run e2e feature branch or main.
+  #       run: |
+  #         echo DEFAULT: E2E test will run with: $E2EBRANCHNAME
+  #         echo "Running on: ${{ steps.branch-name.outputs.current_branch }}"
+  #         if [ -n "$(git ls-remote --heads https://github.com/mangata-finance/mangata-e2e.git ${{ steps.branch-name.outputs.current_branch }} --force --quiet)" ]; then echo "E2EBRANCHNAME=${{ steps.branch-name.outputs.current_branch }}" >> $GITHUB_ENV; echo "MATCH - OK" ; elif [ -n "$(git ls-remote --heads https://github.com/mangata-finance/mangata-e2e.git ${{ github.base_ref }} --force --quiet)" ]; then echo "E2EBRANCHNAME=${{ github.base_ref }}" >> $GITHUB_ENV; echo "MATCH - OK" ;  fi
 
-      - name: Decide if main - branch or parameter
-        # if we have something in e2eBranch - override E2EBranchName, else -> E2EBRANCHNAME , that
-        # by default will be main.
-        run: echo "E2EBRANCHNAME=${{ github.event.inputs.e2eBranch || env.E2EBRANCHNAME }}" >> $GITHUB_ENV
+  #     - name: Decide if main - branch or parameter
+  #       # if we have something in e2eBranch - override E2EBranchName, else -> E2EBRANCHNAME , that
+  #       # by default will be main.
+  #       run: echo "E2EBRANCHNAME=${{ github.event.inputs.e2eBranch || env.E2EBRANCHNAME }}" >> $GITHUB_ENV
 
-      - name: E2E- Get target branch.
-        run: |
-          echo "${{ env.E2EBRANCHNAME }}"
+  #     - name: E2E- Get target branch.
+  #       run: |
+  #         echo "${{ env.E2EBRANCHNAME }}"
 
-      - name: Checkout tests
-        uses: actions/checkout@v2
-        with:
-          repository: mangata-finance/mangata-e2e
-          ref: "${{ env.E2EBRANCHNAME }}"
-          path: "e2eTests"
+  #     - name: Checkout tests
+  #       uses: actions/checkout@v3
+  #       with:
+  #         repository: mangata-finance/mangata-e2e
+  #         ref: "${{ env.E2EBRANCHNAME }}"
+  #         path: e2eTests
 
-      - name: Print parachain docker image reference
-        run: |
-          echo ${{ env.PARACHAIN_DOCKER_IMAGE }}
+  #     - name: Print parachain docker image reference
+  #       run: |
+  #         echo ${{ env.PARACHAIN_DOCKER_IMAGE }}
 
-      - name: Replace parachain docker image reference in config
-        working-directory: launch
-        run: sed -i 's+mangatasolutions/mangata-node:dev+${{ env.PARACHAIN_DOCKER_IMAGE }}+g' config.yml
+  #     - name: Replace parachain docker image reference in config
+  #       working-directory: launch
+  #       run: sed -i 's+mangatasolutions/mangata-node:dev+${{ env.PARACHAIN_DOCKER_IMAGE }}+g' config.yml
 
-      - name: Install parachain launch
-        working-directory: launch
-        run: yarn
+  #     - name: Install parachain launch
+  #       working-directory: launch
+  #       run: yarn
 
-      - name: Generate parachain launch config
-        working-directory: launch
-        run: yarn gen
+  #     - name: Generate parachain launch config
+  #       working-directory: launch
+  #       run: yarn gen
 
-      - name: Stop previous parachain if running
-        working-directory: launch
-        run: yarn down
+  #     - name: Stop previous parachain if running
+  #       working-directory: launch
+  #       run: yarn down
 
-      - name: Start mangata-node parachain
-        working-directory: launch
-        run: yarn up
+  #     - name: Start mangata-node parachain
+  #       working-directory: launch
+  #       run: yarn up
 
-      - name: Install dependencies
-        working-directory: e2eTests
-        run: yarn
+  #     - name: Install dependencies
+  #       working-directory: e2eTests
+  #       run: yarn
 
-      - name: Docker ps
-        run: docker ps
+  #     - name: Docker ps
+  #       run: docker ps
 
-      - name: Sleep for 2 minutes
-        run: sleep 120s #close buffers of videos.
+  #     - name: Sleep for 2 minutes
+  #       run: sleep 120s #close buffers of videos.
 
-      - name: Run tests
-        working-directory: e2eTests
-        run: ${{ matrix.command }}
+  #     - name: Run tests
+  #       working-directory: e2eTests
+  #       run: ${{ matrix.command }}
 
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure() # run this step even if previous step failed
-        with:
-          name: E2E report ${{ matrix.command }} # Name of the check run which will be created
-          path: e2eTests/reports/junit-*.xml # Path to test results
-          reporter: jest-junit # Format of test results
+  #     - name: Test Report
+  #       uses: dorny/test-reporter@v1.6.0
+  #       if: success() || failure() # run this step even if previous step failed
+  #       with:
+  #         name: E2E report ${{ matrix.command }} # Name of the check run which will be created
+  #         path: e2eTests/reports/junit-*.xml # Path to test results
+  #         reporter: jest-junit # Format of test results
 
-      - name: Collect docker logs on failure
-        if: failure()
-        uses: jwalton/gh-docker-logs@v1
-        with:
-          dest: "./logs"
+  #     - name: Collect docker logs on failure
+  #       if: failure()
+  #       uses: jwalton/gh-docker-logs@v2.2.1
+  #       with:
+  #         dest: "./logs"
 
-      - name: Tar logs
-        if: failure()
-        run: tar cvzf ./logs.tgz ./logs
+  #     - name: Tar logs
+  #       if: failure()
+  #       run: tar cvzf ./logs.tgz ./logs
 
-      - name: Create images snapshots
-        if: failure()
-        run: |
-          docker commit  $(docker ps | grep parachain-2110-1 | awk '{print $1}') mangata_test_run/mangata_bob_1
-          docker save  --output=/tmp/mangata_bob_1.tar mangata_test_run/mangata_bob_1
-          docker commit  $(docker ps | grep parachain-2110-0 | awk '{print $1}') mangata_test_run/mangata_alice_1
-          docker save  --output=/tmp/mangata_alice_1.tar mangata_test_run/mangata_alice_1
+  #     - name: Create images snapshots
+  #       if: failure()
+  #       run: |
+  #         docker commit  $(docker ps | grep parachain-2110-1 | awk '{print $1}') mangata_test_run/mangata_bob_1
+  #         docker save  --output=/tmp/mangata_bob_1.tar mangata_test_run/mangata_bob_1
+  #         docker commit  $(docker ps | grep parachain-2110-0 | awk '{print $1}') mangata_test_run/mangata_alice_1
+  #         docker save  --output=/tmp/mangata_alice_1.tar mangata_test_run/mangata_alice_1
 
-      - name: Upload logs  and docker images to GitHub
-        if: failure()
-        uses: actions/upload-artifact@master
-        with:
-          name: logsAndImages
-          path: |
-            ./logs.tgz
-            /tmp/mangata_bob_1.tar
-            /tmp/mangata_alice_1.tar
+  #     - name: Upload logs  and docker images to GitHub
+  #       if: failure()
+  #       uses: actions/upload-artifact@v3.1.1
+  #       with:
+  #         name: logsAndImages
+  #         path: |
+  #           ./logs.tgz
+  #           /tmp/mangata_bob_1.tar
+  #           /tmp/mangata_alice_1.tar
 
-      - name: Stop mangata-node parachain
-        if: always()
-        working-directory: launch
-        run: yarn down
+  #     - name: Stop mangata-node parachain
+  #       if: always()
+  #       working-directory: launch
+  #       run: yarn down
